[package]
name = "stipple-bridge"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
# Brush deps.
brush-incremental.path = "../../crates/brush-incremental"
brush-render.path = "../../crates/brush-render"
brush-app.path = "../brush-app"

tokio = { workspace = true, features = ["io-util", "rt", "rt-multi-thread"] }

env_logger.workspace = true
egui.workspace = true
eframe.workspace = true
anyhow.workspace = true
log.workspace = true
glam.workspace = true
serde_json.workspace = true
image.workspace = true

cxx = "1.0.194"

[build-dependencies]
cxx-build = "1.0.194"

[lints]
workspace = true
